pipeline {
  agent any
  parameters {

    choice(name: 'build_type',
            choises: 'bug fix\nfeature\nrelease',
            description: ''escolha o tipo de build)
  }
  stages {
    stage('Example') {
      steps {
        echo 'Hello'
        echo "${params.build_type}"
      }
    }
  }
}