pipeline {
  agent any
  parameters {
    choice(name: 'build_type',
            choices: 'bug fix\nfeature\nrelease',
            description: 'escolha o tipo de build')

            gitParameter branchFilter: 'origin/(.*)', defaultValue: 'master', name: 'BRANCH', type: 'PT_BRANCH'
  }
  stages {
    stage('Example') {
      steps {
        echo 'Hello'
        echo "${params.build_type}"
      }
    }
  }
}